### ISSUE TITLE
iTunes not updating

### ISSUE THREAD

**Issue by vGruntus** [vbrownbag/www#1]
Greetings. The iTunes podcast feed does not appear to have updated since September 5th, 2016. I can see that new videos have been posted since.

**Comment by jfrappier** [comment]
Thanks for the note @vGruntus - currently our feed to iTunes is a wee bit manually automated, I can see we have a backlog of episodes to post, so they aren't always in sync. I'll annoy @DemitasseNZ after VMworld Barcelona to see if he can kick off the yak shaving scripts to get them uploaded.

**Comment by vGruntus** [comment]
Brilliant! Thank you.

**Comment by DemitasseNZ** [comment]
I found the fault in my process. Updates should start flowing.
I do try not to post more than two episodes per day, so it will be a little while before I catch up.

**Comment by jfrappier** [comment]
Looks like the new episodes have started to get published @vGruntus. Going to close this out but do let us know if there are any other issues.
![updated](https://cloud.githubusercontent.com/assets/6105793/19573976/5ea7f4be-96d6-11e6-8f2a-b235e74d2dd2.PNG)

**Comment by vGruntus** [comment]
Hey @jfrappier, @DemitasseNZ.  I can confirm that the iTunes podcast is now downloading.

Unfortunately @DemitasseNZ, your AWS SA Assoc Dom 1 Pt 5  podcast is not downloading. I have tried the URL directly, however I end up with a 404 not found error. Is the URL incorrect, or is the file missing?

**Comment by DemitasseNZ** [comment]
I've uploaded the file along with another that was missing
Should be a complete set now
