### ISSUE TITLE
VBrownbag podcast feed not using working download links

### ISSUE THREAD

**Issue by fordan** [vbrownbag/www#2]
The podcast feed for VBrownbag (http://virtualnetworkdesign.com/brownbag/brownbags.xml) hasn't been providing working media file URLs since the #vBrownBag US - VMware vSphere 6.7 Upgrade with Nigel Hickey episode.

The podcast XML lists http://s3.us-east-2.amazonaws.com/vbrownbagpodcast/VMware-vSphere-6.7-Upgrade-wit.mp4 as the media file for the vSphere 6.7 Upgrade episode and http://s3.us-east-2.amazonaws.com/vbrownbagpodcast/2018-06-13-20.30-vBrownBag-US.mp4 as the media file for the NSX-T + CNA episode, both of which generate 404 File Not Found errors.

**Comment by jfrappier** [comment]
Thanks - looking into this. Will let you know when it is resolved. Thanks again for letting us know.

**Comment by DemitasseNZ** [comment]
The media files are uploading now.
I will check the next episode more carefully

**Comment by jfrappier** [comment]
Thanks @DemitasseNZ - @fordan let us know if its working yet.

**Comment by fordan** [comment]
Yup, when I checked this morning shortly after DemitasseNZ's message NSX-T was working but not vSphere 6.7 so probably was still uploading. Now both work, thank you both for your prompt help!
