### ISSUE TITLE
Podcast media link incorrect

### ISSUE THREAD

**Issue by fordan** [vbrownbag/www#3]
In the http://virtualnetworkdesign.com/brownbag/brownbags.xml podcast feed, the media link for 7/16 "#vBrownBag US - The VDI Design Guide @vdidesignguide with Johan van Amersfoort @vhojan & Marco van Baggum @vMBaggum" episode points to the media file http://s3.us-east-2.amazonaws.com/vbrownbagpodcast/The-VDI-Design-Guide-%40vdides.mp4. That media file gives a 404 error.

**Comment by jfrappier** [comment]
Thanks - will get that fixed and let you know when it should be good to go.

**Comment by DemitasseNZ** [comment]
Corrected, files is now available on valid URL and downloads for me

**Comment by fordan** [comment]
I was able to download it once I forced my podcast player to reload the XML feed file.

**Comment by jfrappier** [comment]
Thanks @fordan
