### ISSUE TITLE
Podcast feed has missing file for "Governing your Microsoft Azure Environment with Phoummala Schmitt"

### ISSUE THREAD

**Issue by fordan** [vbrownbag/www#4]
The podcast feed at http://feeds.feedburner.com/Professionalvmware-Brownbags has http://feedproxy.google.com/~r/Professionalvmware-Brownbags/~5/zgisiPNhuII/2019-06-05_20.33_vBrownBag_US.mp4 as the link for "Governing your Microsoft Azure Environment with Phoummala Schmitt" and that mp4 link comes up with a "The specified bucket does not exist" error from AWS.

**Comment by jfrappier** [comment]
Thank you @fordan!

**Comment by DemitasseNZ** [comment]
Thanks, a fault in my new automated posting script put the wrong URL in the feed.
The feed is updated, as is my posting script.
