### ISSUE TITLE
Podcast feed broken again

### ISSUE THREAD

**Issue by fordan** [vbrownbag/www#6]
Currently in the podcast feed at http://virtualnetworkdesign.com/brownbag/brownbags.xml (or via http://feeds.feedburner.com/Professionalvmware-Brownbags) I'm seeing 4 podcasts fail to download with a 404 "The specified key does not exist." Those are:

* [VMware NSX over ACI fabric presented by Paul Mancuso](https://s3.us-east-2.amazonaws.com/vbrownbagpodcast/NSX_over_ACI.mp4)
* [VMware Cloud Foundation Lab Constructor (VLC) presented by Heath Johnson](https://s3.us-east-2.amazonaws.com/vbrownbagpodcast/VMware_Cloud_Foundation_Lab_Constructor.mp4)
* [A Tale of Trust presented by Benedikt Frenzel (@BenediktFrenzel)](https://s3.us-east-2.amazonaws.com/vbrownbagpodcast/A_Tale_of_Trust.mp4)
* [Falling from the Clouds - Basics, Pitfalls & What You Didn't Know About Azure & AWS](https://s3.us-east-2.amazonaws.com/vbrownbagpodcast/Falling_from_the_Clouds.mp4)

**Comment by DemitasseNZ** [comment]
Thank you, I will take a look later this week & correct the URLs

**Comment by DemitasseNZ** [comment]
Thanks for including the URLs that were failing.
All four episodes should now download successfully
