### ISSUE TITLE
Podcast feed broken

### ISSUE THREAD

**Issue by fordan** [vbrownbag/www#7]
Me again!

The latest vBrownbag added, [What's new with vCenter Server 7 presented by Nigel Hickey](https://s3.us-east-2.amazonaws.com/vbrownbagpodcast/What's_new_with_vCenter_Server_7.mp4), is failing with a 404/Key not found at  http://virtualnetworkdesign.com/brownbag/brownbags.xml & http://feeds.feedburner.com/Professionalvmware-Brownbags

**Comment by jfrappier** [comment]
You're hired as QA engineer!

**Comment by fordan** [comment]
Since I'm stuck at home and trying to learn Python I built a quick program to parse the feed and verify file availability and found a few others that are old enough that my podcast app isn't complaining about them:

404 Not Found error in Podcast entry:
#vBrownBag US - vSphere Validated Designs Episode 2 with Ryan Johnson @tenthirtyam and Nick Marshall @nickmarshall9
with a URL of:
http://s3.us-east-2.amazonaws.com/vbrownbagpodcast/2017-02-22-20.35-vBrownBag-US.mp4

404 Not Found error in Podcast entry:
#vBrownBag US - CCNA DC - Part 11: Unified Computing with Jarrett Kulm @JK47theweapon
with a URL of:
http://s3.us-east-2.amazonaws.com/vbrownbagpodcast/2016-04-20-19.31-#vBrownBag-US.mp4

404 Not Found error in Podcast entry:
#vBrownBag US - CCNA DC - Part 10: DC Virtualization with Joel Sprague @jwsconsult
with a URL of:
http://s3.us-east-2.amazonaws.com/vbrownbagpodcast/2016-04-13-20.30-#vBrownBag-US.mp4

**Comment by jfrappier** [comment]
That is really cool! Nice work! You should do a #vBrownbag episode on how you did it :)

**Comment by DemitasseNZ** [comment]
Thanks @fordan, the feed validation told me some episodes had missing media, but never told me which items. Unfortunately, I don't have a backup of older media so the only option is to remove the episode.
I also worked out why all the new episodes were 404, the default upload directory was wrong. 
I should change the upload to use the AWS CLI or PowerShell SDK.
Nigel's episode is uploading to the right place & after that I will put up an updated XML

**Comment by fordan** [comment]
I reran my program and the feed seems clean now.

In case it's useful, here's my program. It needs the requests and feedparser libraries installed to operate since they do the heavy lifting.

```
#!/usr/bin/env python3

import requests
from feedparser import parse

#feedurl='http://feeds.feedburner.com/Professionalvmware-Brownbags'
feedurl='http://virtualnetworkdesign.com/brownbag/brownbags.xml'

print("Grabbing & parsing podcast feed")
podcastfeed = parse(feedurl)

print("Checking each podcast enclosure")
for e in podcastfeed.entries: #Iterate through each podcast entry
    for item in e.enclosures: #In theory a podcast entry might have more than one enclosure
        test = requests.request('HEAD', item.href)
        if not test.ok:
            print(f"{test.status_code} {test.reason} error in Podcast entry:\n{e.title}\nwith a URL of:\n{item.href}\n")
```
