### ISSUE TITLE
Latest vBrownbag not showing up in podcast feed

### ISSUE THREAD

**Issue by fordan** [vbrownbag/www#8]
The latest vBrownbag, "Using PowerBI to report on your infrastructure presented by Greg Bates" has been up on YouTube for a number of days but hasn't shown up on the podcast feed yet.

**Comment by fordan** [comment]
PowerBI was added, but the three vBrownbags done since are not in the podcast feed.

**Comment by DemitasseNZ** [comment]
Thanks, found another fault in my automation. The three subsequent episodes will be there once the caches all refresh
